### ISSUE TITLE
Shader code compilation issue on android browsers only

### ISSUE THREAD

**Issue by Abuzar-Thanvi** [pmndrs/drei-vanilla#71]
- `three` 0.164.1:
- `@pmndrs/vanilla` 1.19.1:
- `node` 20.16.0:
- `npm` (or `yarn`) 10.8.1:

### Problem description:

**_THIS OCCURS ONLY ON ANDROID BROWSERS_**

**_Note:_** This issue can be reproduced on : https://vis-prime.github.io/explore-vanilla-drei/?scene=Cloud

The shader code for clouds class (drei-vanilla/src/core/Cloud.ts) is causing an error due to a conflict in names for shader attributes in the CloudMaterialMaker function

Below is the complete error message

_three.module.js:20131 THREE.WebGLProgram: Shader Error 0 - VALIDATE_STATUS false

Material Name: 
Material Type: MeshLambertMaterial

Program Info Log: Name conflicts between an uniform and an attribute: opacity_

### Suggested solution:

Just rename the repeated attribute and all its used instances and it'll be fixed

**Comment by vis-prime** [comment]
Confirmed



<img width="611" alt="Screenshot 2024-08-28 235938" src="https://github.com/user-attachments/assets/66c7be1c-90f0-48dc-a044-55a54cb75318">

Renaming the attribute removes the error but the cloud mesh is fully invisible, so that's not the way.

Happens on the react version too https://drei.pmnd.rs/?path=/story/staging-cloud--cloud-st
